class_name Hud
extends Control

## On-screen controls: view rotation, board flip, and a menu entry point,
## plus whose turn it is.
##
## The HUD knows nothing about the camera or the game. It emits intents and
## Main routes them, which keeps it reusable and lets the whole control layer
## be tested without a viewport. Icons are generated by Icons so there is no
## imported art and every glyph matches the palette.
##
## Layout is right-hand vertical: a column of icon buttons centred against the
## right edge, with the menu button alone in the top-right corner so it never
## crowds the view controls.

## Emitted with +1 to rotate right, -1 to rotate left.
signal rotate_requested(direction: int)
## Emitted when the player asks for the default framing back.
signal reset_view_requested
## Emitted to swap the board to the other player's point of view.
signal flip_requested
## Emitted by the menu button. The settings screen will listen to this.
signal menu_requested
## Emitted when the mic button is toggled, with the requested state. Voice
## transport is not built yet, so nothing listens; the control exists so the
## affordance is settled before the audio plumbing lands.
signal mic_toggled(enabled: bool)

## The voice controls are hidden entirely when there is nobody to talk to, so
## the solo board keeps the space for the board itself.
@onready var voice_row: Control = %VoiceRow
@onready var mic_ring: Panel = %MicRing
@onready var remote_dot: Panel = %RemoteDot

@onready var turn_label: Label = %TurnLabel
@onready var control_column: VBoxContainer = %ControlColumn
@onready var rotate_left_button: Button = %RotateLeftButton
@onready var rotate_right_button: Button = %RotateRightButton
@onready var flip_button: Button = %FlipButton
@onready var reset_button: Button = %ResetButton
@onready var menu_button: Button = %MenuButton
@onready var mic_button: Button = %MicButton

## Whether the mic control is currently presenting as live.
var mic_enabled := false

## Voice controls only appear once a real opponent is on the other end.
var voice_visible := false

## Icon-only buttons still need a comfortable tap target.
const TOUCH_SIZE := Vector2(64.0, 64.0)
## How far the glyph is inset from the button's edges. The glyph lives in an
## inset TextureRect rather than on the Button itself: Button's own icon
## layout expands first and clamps afterwards, which leaves the draw offset
## derived from the pre-clamp size and visibly off-centre. A rect anchored to
## the button with a fixed inset and KEEP_ASPECT_CENTERED is centred by
## construction, at any texture resolution.
const ICON_INSET := 12.0

## Where the voice control sits horizontally, as a fraction of the screen
## width. The exact midpoint of the move count and the menu is 0.75; this is
## deliberately past it, because the label is a wide block of text while the
## menu is a small button, so a true 50/50 reads as closer to the label than
## it actually is. Tuning, not derivation, hence a named value.
const VOICE_ANCHOR := 0.82


func _ready() -> void:
	bind()


## Shows whose turn it is. Call after any move.
func set_turn(side: int, moves: int) -> void:
	if turn_label == null:
		return
	var who := "White" if side == BoardState.LIGHT else "Black"
	turn_label.text = "%s to move    ·    %d %s" % [
		who, moves, "move" if moves == 1 else "moves"
	]


## Wires the buttons. Safe to call twice, so tests can drive the HUD right
## after instantiation without waiting for _ready.
func bind() -> void:
	if rotate_left_button == null:
		return
	_connect(rotate_left_button, _on_rotate_left)
	_connect(rotate_right_button, _on_rotate_right)
	_connect(flip_button, _on_flip)
	_connect(reset_button, _on_reset)
	_connect(menu_button, _on_menu)
	_connect(mic_button, _on_mic)


func _connect(button: Button, method: Callable) -> void:
	if button != null and not button.pressed.is_connected(method):
		button.pressed.connect(method)


func _on_rotate_left() -> void:
	rotate_requested.emit(-1)


func _on_rotate_right() -> void:
	rotate_requested.emit(1)


func _on_flip() -> void:
	flip_requested.emit()


func _on_reset() -> void:
	reset_view_requested.emit()


func _on_menu() -> void:
	menu_requested.emit()


## Swaps the glyph between live and muted rather than tinting one, so "you are
## not speaking" cannot be misread as a styling state.
func set_mic_enabled(enabled: bool) -> void:
	mic_enabled = enabled
	if mic_button == null:
		return
	var glyph := mic_button.get_node_or_null("Glyph") as TextureRect
	if glyph != null:
		glyph.texture = Icons.mic() if enabled else Icons.mic_off()
	# The ring is a second, non-colour channel for the same fact, so the state
	# still reads if the glyph is hard to make out against the board.
	if mic_ring != null:
		mic_ring.visible = enabled


## Shows or hides the whole voice cluster. Turning it off also mutes, so the
## mic can never come back live behind a hidden button.
func set_voice_visible(shown: bool) -> void:
	voice_visible = shown
	if voice_row != null:
		voice_row.visible = shown
	if not shown:
		set_mic_enabled(false)
		set_remote_speaking(false)


## Lights the dot that shows the opponent is transmitting. Kept separate from
## the mic glyph so you can tell 'they are talking' from 'I am unmuted'.
func set_remote_speaking(speaking: bool) -> void:
	if remote_dot != null:
		remote_dot.visible = speaking and voice_visible


func _on_mic() -> void:
	set_mic_enabled(not mic_enabled)
	mic_toggled.emit(mic_enabled)