class_name Hud
extends Control

## On-screen controls: view rotation, board flip, and a menu entry point,
## plus whose turn it is.
##
## The HUD knows nothing about the camera or the game. It emits intents and
## Main routes them, which keeps it reusable and lets the whole control layer
## be tested without a viewport. Icons are generated by Icons so there is no
## imported art and every glyph matches the palette.
##
## Layout is right-hand vertical: a column of icon buttons centred against the
## right edge, with the menu button alone in the top-right corner so it never
## crowds the view controls.

## Emitted with +1 to rotate right, -1 to rotate left.
signal rotate_requested(direction: int)
## Emitted when the player asks for the default framing back.
signal reset_view_requested
## Emitted to swap the board to the other player's point of view.
signal flip_requested
## Emitted by the menu button. The settings screen will listen to this.
signal menu_requested

@onready var turn_label: Label = %TurnLabel
@onready var control_column: VBoxContainer = %ControlColumn
@onready var rotate_left_button: Button = %RotateLeftButton
@onready var rotate_right_button: Button = %RotateRightButton
@onready var flip_button: Button = %FlipButton
@onready var reset_button: Button = %ResetButton
@onready var menu_button: Button = %MenuButton

## Icon-only buttons still need a comfortable tap target.
const TOUCH_SIZE := Vector2(64.0, 64.0)


func _ready() -> void:
	bind()


## Shows whose turn it is. Call after any move.
func set_turn(side: int, moves: int) -> void:
	if turn_label == null:
		return
	var who := "White" if side == BoardState.LIGHT else "Black"
	turn_label.text = "%s to move    ·    %d %s" % [
		who, moves, "move" if moves == 1 else "moves"
	]


## Wires the buttons. Safe to call twice, so tests can drive the HUD right
## after instantiation without waiting for _ready.
func bind() -> void:
	if rotate_left_button == null:
		return
	_connect(rotate_left_button, _on_rotate_left)
	_connect(rotate_right_button, _on_rotate_right)
	_connect(flip_button, _on_flip)
	_connect(reset_button, _on_reset)
	_connect(menu_button, _on_menu)


func _connect(button: Button, method: Callable) -> void:
	if button != null and not button.pressed.is_connected(method):
		button.pressed.connect(method)


func _on_rotate_left() -> void:
	rotate_requested.emit(-1)


func _on_rotate_right() -> void:
	rotate_requested.emit(1)


func _on_flip() -> void:
	flip_requested.emit()


func _on_reset() -> void:
	reset_view_requested.emit()


func _on_menu() -> void:
	menu_requested.emit()