class_name Hud
extends Control

## On-screen controls: view rotation, board flip, and a menu entry point,
## plus whose turn it is.
##
## The HUD knows nothing about the camera or the game. It emits intents and
## Main routes them, which keeps it reusable and lets the whole control layer
## be tested without a viewport. Icons are generated by Icons so there is no
## imported art and every glyph matches the palette.
##
## Layout is right-hand vertical: a column of icon buttons centred against the
## right edge, with the menu button alone in the top-right corner so it never
## crowds the view controls.

## Emitted with +1 to rotate right, -1 to rotate left.
signal rotate_requested(direction: int)
## Emitted when the player asks for the default framing back.
signal reset_view_requested
## Emitted to swap the board to the other player's point of view.
signal flip_requested
## Emitted by the menu button. The settings screen will listen to this.
signal menu_requested
## The three states the mic control can present. Requesting is separate from
## live on purpose: asking for voice and speaking are different things, and
## collapsing them would leave the player unsure whether anyone heard them.
enum VoiceState {
	OFF,          ## muted, no voice
	REQUESTING,   ## asking the other side for voice
	LIVE,         ## transmitting
}

## Emitted whenever the mic control changes state. Voice transport is not built
## yet, so nothing listens; the control exists so the affordance is settled
## before the audio plumbing lands.
signal voice_state_changed(state: VoiceState)

## The voice controls are hidden entirely when there is nobody to talk to, so
## the solo board keeps the space for the board itself.
@onready var voice_row: Control = %VoiceRow
@onready var mic_ring: Panel = %MicRing
@onready var remote_dot: Panel = %RemoteDot
@onready var captured_light: HFlowContainer = %CapturedLight
@onready var captured_dark: HFlowContainer = %CapturedDark

@onready var turn_label: Label = %TurnLabel
@onready var control_column: VBoxContainer = %ControlColumn
@onready var rotate_left_button: Button = %RotateLeftButton
@onready var rotate_right_button: Button = %RotateRightButton
@onready var flip_button: Button = %FlipButton
@onready var reset_button: Button = %ResetButton
@onready var menu_button: Button = %MenuButton
@onready var mic_button: Button = %MicButton

## Current presentation state of the mic control.
var voice_state := VoiceState.OFF

## Voice controls only appear once a real opponent is on the other end.
var voice_visible := false

## Icon-only buttons still need a comfortable tap target.
const TOUCH_SIZE := Vector2(64.0, 64.0)
## How far the glyph is inset from the button's edges. The glyph lives in an
## inset TextureRect rather than on the Button itself: Button's own icon
## layout expands first and clamps afterwards, which leaves the draw offset
## derived from the pre-clamp size and visibly off-centre. A rect anchored to
## the button with a fixed inset and KEEP_ASPECT_CENTERED is centred by
## construction, at any texture resolution.
const ICON_INSET := 12.0

## How far the menu button sits in from the right edge.
const MENU_INSET := 84.0

## Distance from the centre of the mic to the centre of the menu.
##
## Deliberately a gap rather than a fraction of screen width: the two controls
## belong to the same corner, so they should hold their spacing as the screen
## narrows. An anchor fraction drifts away from the menu on narrow displays,
## which is the same complaint as the original fixed offset.
const VOICE_GAP := 160.0


func _ready() -> void:
	bind()


## Shows whose turn it is. Call after any move.
func set_turn(side: int, moves: int) -> void:
	if turn_label == null:
		return
	var who := "White" if side == BoardState.LIGHT else "Black"
	turn_label.text = "%s to move    ·    %d %s" % [
		who, moves, "move" if moves == 1 else "moves"
	]


## Wires the buttons. Safe to call twice, so tests can drive the HUD right
## after instantiation without waiting for _ready.
func bind() -> void:
	if rotate_left_button == null:
		return
	_connect(rotate_left_button, _on_rotate_left)
	_connect(rotate_right_button, _on_rotate_right)
	_connect(flip_button, _on_flip)
	_connect(reset_button, _on_reset)
	_connect(menu_button, _on_menu)
	_connect(mic_button, _on_voice)


func _connect(button: Button, method: Callable) -> void:
	if button != null and not button.pressed.is_connected(method):
		button.pressed.connect(method)


func _on_rotate_left() -> void:
	rotate_requested.emit(-1)


func _on_rotate_right() -> void:
	rotate_requested.emit(1)


func _on_flip() -> void:
	flip_requested.emit()


func _on_reset() -> void:
	reset_view_requested.emit()


func _on_menu() -> void:
	menu_requested.emit()


## Swaps the glyph between live and muted rather than tinting one, so "you are
## not speaking" cannot be misread as a styling state.
func set_voice_state(state: VoiceState) -> void:
	voice_state = state
	if mic_button != null:
		var glyph := mic_button.get_node_or_null("Glyph") as TextureRect
		if glyph != null:
			match state:
				VoiceState.REQUESTING:
					glyph.texture = Icons.mic_signal()
				VoiceState.LIVE:
					glyph.texture = Icons.mic()
				_:
					glyph.texture = Icons.mic_off()
	# The ring marks live only. A request must not look like a live mic, or
	# the other player will talk over someone who is merely asking.
	if mic_ring != null:
		mic_ring.visible = state == VoiceState.LIVE


func is_voice_live() -> bool:
	return voice_state == VoiceState.LIVE


func _on_voice() -> void:
	# Off, then asking, then transmitting. Requesting sits in the middle so the
	# common single tap asks for voice instead of silently transmitting, which
	# is the less surprising thing to do to the opponent.
	set_voice_state(voice_state + 1 if voice_state < VoiceState.LIVE else VoiceState.OFF)
	voice_state_changed.emit(voice_state)


## Shows or hides the whole voice cluster. Turning it off also mutes, so the
## mic can never come back live behind a hidden button.
func set_voice_visible(shown: bool) -> void:
	voice_visible = shown
	if voice_row != null:
		voice_row.visible = shown
	if not shown:
		set_voice_state(VoiceState.OFF)
		set_remote_speaking(false)


## Size of one captured-piece silhouette in a tray.
const CAPTURED_SIZE := Vector2(32.0, 32.0)

## Repaints both capture trays from scratch.
##
## Trays are keyed by the side that *did the capturing*, and the glyphs are
## tinted for the piece that was taken, so the colour of the silhouettes alone
## tells you who took what without needing a label.
func set_captured(took_light: Array[int], took_dark: Array[int]) -> void:
	_fill_capture_row(captured_light, took_light)
	_fill_capture_row(captured_dark, took_dark)


func _fill_capture_row(row: HFlowContainer, codes: Array[int]) -> void:
	if row == null:
		return
	for child in row.get_children():
		row.remove_child(child)
		child.queue_free()
	# Grouped by piece type rather than capture order: a row that reshuffles
	# every time an unrelated piece falls is harder to count at a glance, and
	# the order things died in is not what the tray is for.
	var grouped := codes.duplicate()
	grouped.sort_custom(func(a: int, b: int) -> bool:
		return BoardState.decode(a).x < BoardState.decode(b).x)
	for code in grouped:
		var decoded := BoardState.decode(code)
		if decoded.x < 0:
			continue
		var icon := TextureRect.new()
		icon.texture = PieceGlyphs.glyph(decoded.x)
		icon.custom_minimum_size = CAPTURED_SIZE
		icon.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
		icon.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
		icon.mouse_filter = Control.MOUSE_FILTER_IGNORE
		icon.modulate = PieceGlyphs.tint_for(decoded.y)
		row.add_child(icon)


## Lights the dot that shows the opponent is transmitting. Kept separate from
## the mic glyph so you can tell 'they are talking' from 'I am unmuted'.
func set_remote_speaking(speaking: bool) -> void:
	if remote_dot != null:
		remote_dot.visible = speaking and voice_visible
